version: '3'
services:
  redis_db:
    image: redis:latest
    container_name: redis_db
    hostname: redis_db
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    links:
      - redis_db
    depends_on:
      - redis_db
